management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # Добавляем prometheus для сбора метрик
  metrics:
    export:
      prometheus:
        enabled: true                    # Включаем экспорт в формат Prometheus
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    prometheus:
      enabled: true

ml:
  model:
    enabled: true
    tokenizer:
      path: file:/app/models/tokenizer.json
    embedding:
      path: file:/app/models/embedding_model.onnx