spring:
  application:
    name: semantic-search

  datasource:
    url: jdbc:postgresql://192.168.1.45:5432/ml_platform?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

ml:
  model:
    enabled: true
    tokenizer:
      path: classpath:models/tokenizer.json
    embedding:
      path: classpath:models/embedding_model.onnx

management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true

logging:
  level:
    com.example.inference: DEBUG