plugins {
    id 'com.google.protobuf'
}

description = 'semantic-search-worker'

springBoot {     // для генерации файла build-info.properties внутри JAR.
    buildInfo()  // Он добавляет в /actuator/info информацию о версии и времени сборки.
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    implementation libpacks.springBootCommon
    implementation libpacks.embedding
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation "org.springframework.boot:spring-boot-starter-liquibase"
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'net.devh:grpc-spring-boot-starter:3.1.0.RELEASE'
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation libpacks.test
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'com.h2database:h2:2.3.232'
    testImplementation 'org.mockito:mockito-core:5.3.1'
}

bootJar {
    exclude('**/models/**')
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.24.4'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.74.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {
                // Убираем аннотацию @Generated, чтобы не было проблем с javax/jakarta
                option 'jakarta_omit'
                // Альтернативно: option '@generated=omit'
            }
        }
    }
}

// Указываем, где искать .proto файлы (они лежат в common)
sourceSets {
    main {
        proto {
            srcDirs '../common/src/main/proto', 'src/main/proto'
        }
    }
}